### PR TITLE
pkg/sqlite: use consistent starting depth when building channel_entry table

### LINKED ISSUE #867: opm add with the options --from-index and --mode semver is not creating replaces edges
#### Description
By using `OPM index add --mode semver,` the OPM CLI draws replaces edges to form a linear chain between versions based on semver ordering. We can use the command `opm alpha list bundles quay.io/operatorhubio/catalog:latest <package-name>` to check it.

All works fine if we create an index from scratch and add the bundles with the option `--mode semver`. **However, it does not draw the replaces edges when the option `--from-index` is used**. Note that when the bundles are added using the option `--from-index` is and we list the bundles, we can check the skips instead of replaces, see:

```sh
$ opm alpha list bundles quay.io/openshift-community-operators/catalog:v4.9 cert-manager
 WARN[0002] DEPRECATION NOTICE:
 Sqlite-based catalogs and their related subcommands are deprecated. Support for
 them will be removed in a future release. Please migrate your catalog workflows
 to the new file-based catalog format.
 PACKAGE CHANNEL BUNDLE REPLACES SKIPS SKIP RANGE IMAGE
 cert-manager stable cert-manager.v1.4.0 quay.io/openshift-community-operators/cert-manager:v1.4.0
 cert-manager stable cert-manager.v1.4.1 cert-manager.v1.4.0 quay.io/openshift-community-operators/cert-manager:v1.4.1
 cert-manager stable cert-manager.v1.4.2 cert-manager.v1.4.1 quay.io/openshift-community-operators/cert-manager:v1.4.2
 cert-manager stable cert-manager.v1.4.3 cert-manager.v1.4.2 quay.io/openshift-community-operators/cert-manager:v1.4.3
 cert-manager stable cert-manager.v1.4.4 cert-manager.v1.4.3 quay.io/openshift-community-operators/cert-manager:v1.4.4
 cert-manager stable cert-manager.v1.5.3 cert-manager.v1.4.4 quay.io/openshift-community-operators/cert-manager:v1.5.3
 cert-manager stable cert-manager.v1.5.4 cert-manager.v1.5.3 quay.io/openshift-community-operators/cert-manager:v1.5.4
 cert-manager stable cert-manager.v1.6.0 cert-manager.v1.5.4 quay.io/openshift-community-operators/cert-manager:v1.6.0
 cert-manager stable cert-manager.v1.6.1 cert-manager.v1.6.0 quay.io/openshift-community-operators/cert-manager:v1.6.1
```

#### How to reproduce

1) Copy the `registry.redhat.io/redhat/community-operator-index` to tmp location

```
skopeo copy registry.redhat.io/redhat/community-operator-index:v4.9 docker://quay.io/operator_testing/xxx:latest
```

2) Remove the package cert-manager and publish the tmp image

```
opm index rm --operators cert-manager -t quay.io/operator_testing/xxx:latest -c docker --from-index quay.io/operator_testing/xxx:latest
```

```
docker push quay.io/operator_testing/xxx:latest
```

3) Add all bundles with the `index-from` and `--mode semver` options

```
opm index add --bundles quay.io/openshift-community-operators/cert-manager:v1.4.0,quay.io/openshift-community-operators/cert-manager:v1.4.1,quay.io/openshift-community-operators/cert-manager:v1.4.2,quay.io/openshift-community-operators/cert-manager:v1.4.3,quay.io/openshift-community-operators/cert-manager:v1.4.4,quay.io/openshift-community-operators/cert-manager:v1.5.3,quay.io/openshift-community-operators/cert-manager:v1.5.4,quay.io/openshift-community-operators/cert-manager:v1.6.0,quay.io/openshift-community-operators/cert-manager:v1.6.1 -t quay.io/operator_testing/xxx:latest --mode semver -c docker --from-index quay.io/operator_testing/xxx:latest
```

```
docker push quay.io/operator_testing/xxx:latest
```

4) Run the command to list the bundles 

```
./opm alpha list bundles quay.io/operator_testing/xxx:latest cert-manager
ubuntu@ip-172-31-29-117:~$ ./opm alpha list bundles quay.io/operator_testing/xxx:latest cert-manager
WARN[0005] DEPRECATION NOTICE:
Sqlite-based catalogs and their related subcommands are deprecated. Support for
them will be removed in a future release. Please migrate your catalog workflows
to the new file-based catalog format. 
PACKAGE       CHANNEL  BUNDLE               REPLACES  SKIPS                SKIP RANGE  IMAGE
cert-manager  stable   cert-manager.v1.4.0                                             quay.io/openshift-community-operators/cert-manager:v1.4.0
cert-manager  stable   cert-manager.v1.4.1            cert-manager.v1.4.0              quay.io/openshift-community-operators/cert-manager:v1.4.1
cert-manager  stable   cert-manager.v1.4.2            cert-manager.v1.4.1              quay.io/openshift-community-operators/cert-manager:v1.4.2
cert-manager  stable   cert-manager.v1.4.3            cert-manager.v1.4.2              quay.io/openshift-community-operators/cert-manager:v1.4.3
cert-manager  stable   cert-manager.v1.4.4            cert-manager.v1.4.3              quay.io/openshift-community-operators/cert-manager:v1.4.4
cert-manager  stable   cert-manager.v1.5.3            cert-manager.v1.4.4              quay.io/openshift-community-operators/cert-manager:v1.5.3
cert-manager  stable   cert-manager.v1.5.4            cert-manager.v1.5.3              quay.io/openshift-community-operators/cert-manager:v1.5.4
cert-manager  stable   cert-manager.v1.6.0            cert-manager.v1.5.4              quay.io/openshift-community-operators/cert-manager:v1.6.0
cert-manager  stable   cert-manager.v1.6.1            cert-manager.v1.6.0              quay.io/openshift-community-operators/cert-manager:v1.6.1
```

#### What is the consequence of this issue? 

OLM is unable to upgrade the Operators distributed, which ought to use the semver mode. 

Operator bundles distributed on community repos: 
- [https://github.com/k8s-operatorhub/community-operators](https://github.com/k8s-operatorhub/community-operators)(which is the source of the image `quay.io/operatorhubio/catalog:latest`) 
- and [https://github.com/redhat-openshift-ecosystem/community-operators-prod](https://github.com/redhat-openshift-ecosystem/community-operators-prod) (which is the source of the image  `registry.redhat.io/redhat/community-operator-index`) 

which are configured to use the semver mode ( see an e.g.: https://github.com/k8s-operatorhub/community-operators/blob/main/operators/cert-manager/ci.yaml#L2) after being added with the option `--mode semver` are not with replaces edges as expected which do not allow them to be upgraded via OLM. See: https://github.com/k8s-operatorhub/community-operators/issues/119

The tests can be done with cert-manager (https://github.com/k8s-operatorhub/community-operators/blob/main/operators/cert-manager/ci.yaml#L2);

#### Opm version 

1.19.1

#### Aditional Context

- By speaking with @joelanford he was also able to reproduce it with the opm registry commands
- He also checks the code, and he believes that the problem here is:
So, by creating a DB from scratch, minDepth is 1, and ListBundles works correctly.
However, when we use the flag `-from-index`, an existent index, where any channel in the catalog has a depth of 0, this problem will happen, which shows that the semver graph builder starts initial depth at one and not 0.

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
When building the channel_entry table, always using a starting depth of 0. 

**Motivation for the change:**
This is important because the ListBundles query makes an assumption that all packages in the database will have the same minimum depth.

Closes #867 

Signed-off-by: Joe Lanford <joe.lanford@gmail.com

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [x] Commit messages sensible and descriptive

### CODE REVIEW

File: pkg/sqlite/load_test.go [hunk 1]
```diff
@@ -154,6 +155,71 @@ func TestAddPackageChannels(t *testing.T) {
...
+		graph, err := graphLoader.Generate(b.Package)
+		require.Conditionf(t, func() bool {
+			return err == nil || errors.Is(err, registry.ErrPackageNotInDatabase)
+		}, "got unexpected error: %v", err)
+		bundleLoader := registry.BundleGraphLoader{}
+		updatedGraph, err := bundleLoader.AddBundleToGraph(b, graph, &registry.AnnotationsFile{Annotations: *b.Annotations}, false)
+		require.NoError(t, err)
+		err = store.AddBundleSemver(updatedGraph, b)
+		require.NoError(t, err)
+	}
```
Comment (joelanford) [inline pkg/sqlite/load_test.go:202]: I don't love that all of this code is in the test. It seems like this should be better encapsulated in non-test code. I suppose I could re-write the test using the [DirectoryPopulator](https://github.com/operator-framework/operator-registry/blob/28aa6545b5c24c1674b9a09194f9df7b9efb8031/pkg/registry/populator.go#L41) abstraction, but that would require using the `imageDirMap` and putting a bunch of bundle directories to disk during the test.

We could also look at making [this](https://github.com/operator-framework/operator-registry/blob/28aa6545b5c24c1674b9a09194f9df7b9efb8031/pkg/registry/populator.go#L170-L175) something that could be more easily called in a test.

I'm just not sure it's worth it given all of this code is deprecated.

**Review by perdasilva — APPROVED** [review]
/lgtm

File: pkg/sqlite/load.go [hunk 2]
```diff
@@ -424,7 +426,7 @@ func (s *sqlLoader) AddPackageChannelsFromGraph(graph *registry.Package) error {
 	// update each channel's graph
 	for channelName, channel := range graph.Channels {
 		currentNode := channel.Head
-		depth := 1
+		depth := startDepth
```
Comment (dinhxuanvu) [inline pkg/sqlite/load.go:429]: I assume `depth := 1` is a bug and we want the depth starting with 0?

File: pkg/sqlite/load.go [hunk 3]
```diff
@@ -495,7 +497,7 @@ func (s *sqlLoader) AddPackageChannelsFromGraph(graph *registry.Package) error {
 
 			// we got to the end of the channel graph
 			if nextNode.IsEmpty() {
-				if len(channel.Nodes) != depth {
+				if len(channel.Nodes)+startDepth-1 != depth {
```
Comment (dinhxuanvu) [inline pkg/sqlite/load.go:500]: Would be nice to have a comment explaining this addition.

File: pkg/sqlite/load.go [hunk 4]
```diff
@@ -620,7 +622,7 @@ func (s *sqlLoader) addPackageChannels(tx *sql.Tx, manifest registry.PackageMani
 		}
 
 		channelEntryCSVName := c.CurrentCSVName
-		depth := 1
+		depth := startDepth + 1
```
Comment (dinhxuanvu) [inline pkg/sqlite/load.go:625]: Would be nice to add a comment to explain that we already add the currentCSV at depth = 0 so now the depth is at 1. Honestly, this entire section of code is lacking of comments but it is not the main purpose of this PR to address that.

**Review by dinhxuanvu — COMMENTED** [review]
Looking good. A few comments.

**Comment by joelanford** [comment]
/hold
So I can address some comments.

File: pkg/sqlite/load.go (hunk 2 above)
Comment (joelanford) [reply pkg/sqlite/load.go:429]: Correct.

File: pkg/sqlite/load.go (hunk 4 above)
Comment (joelanford) [reply pkg/sqlite/load.go:625]: I'll add a comment about this line, but I don't think I'm prepared to add comments for the entire function (nor should we in this PR since this function is functionally identical, since `startDepth` is 0)

**Review by dinhxuanvu — APPROVED** [review]
Satisfied with the latest changes.
/lgtm
