### PR TITLE
Check only for new bundles on add

### LINKED ISSUE #799: opm add pruning error is unclear
opm add warns when an add operation prunes a bundle expected on an index but the error message is unclear.

```
Failed to add the bundles to the index image: [added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:1470d60ca59fef22b776f1581c12d3bb06949d071d07a9cdd97a37a840ed905c pruned from package amq7-interconnect-operator, channel 1.2.0: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:4e84d9b68d37e663025905e46245abc605d1354c61ccd2a7e1583961fde28eb5 pruned from package amq7-interconnect-operator, channel 1.2.0: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:ec4cbd00237d61e552fe65804b569f78035eed09bdca47bdcdbff831d9484ca7 pruned from package amq7-interconnect-operator, channel 1.2.0: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:b2f1961f30a612edb84fac79211d5c54843c0478235839f83018c92cb428d165 pruned from package amq7-interconnect-operator, channel 1.2.0: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:15723f36c4ef130b25681367a8425f542475b0258122a04cc332872a4273eec7 pruned from package amq7-interconnect-operator, channel 1.2.0: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:afe43efe442ccd8d3c0d3181b5a23d683809703a0a374dbfecf91d0322cf9781 pruned from package amq7-interconnect-operator, channel 1.2.0: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:afe43efe442ccd8d3c0d3181b5a23d683809703a0a374dbfecf91d0322cf9781 pruned from package amq7-interconnect-operator, channel 1.10.x: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:1470d60ca59fef22b776f1581c12d3bb06949d071d07a9cdd97a37a840ed905c pruned from package amq7-interconnect-operator, channel 1.10.x: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:4e84d9b68d37e663025905e46245abc605d1354c61ccd2a7e1583961fde28eb5 pruned from package amq7-interconnect-operator, channel 1.10.x: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:ec4cbd00237d61e552fe65804b569f78035eed09bdca47bdcdbff831d9484ca7 pruned from package amq7-interconnect-operator, channel 1.10.x: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:b2f1961f30a612edb84fac79211d5c54843c0478235839f83018c92cb428d165 pruned from package amq7-interconnect-operator, channel 1.10.x: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2), added bundle registry.redhat.io/amq7/amq-interconnect-operator-metadata@sha256:15723f36c4ef130b25681367a8425f542475b0258122a04cc332872a4273eec7 pruned from package amq7-interconnect-operator, channel 1.10.x: this may be due to incorrect channel head (amq7-interconnect-operator.v1.10.2)]
```

The pruned bundle may not necessarily be a newly added bundle, it can also be an existing bundle that has no path to any of the new bundles on all shared channels.

### PR DESCRIPTION
**Pull request by ankitathomas**
Check only for pruning of newly added bundles, allow existing bundles to be silently dropped in case of no specified paths

Also, update pruning error for clarity

Closes #799

### CODE REVIEW

**Comment by bparees** [comment]
@ankitathomas @kevinrizza @joelanford I think this is a good example of where i'd have expected some sort of "opm add" CI test gating to have prevented the original change(the one that regressed the behavior by erroring out on any pruned bundle) from going in.

File: pkg/lib/registry/registry.go [hunk 1]
```diff
@@ -399,34 +393,57 @@ func checkForBundlePaths(querier registry.GRPCQuery, bundlePaths []string) ([]st
...
+// check for the presence of newly added bundles after a replaces-mode add.
+func checkForBundles(ctx context.Context, q *sqlite.SQLQuerier, g registry.GraphLoader, required []*registry.Bundle) error {
 	var errs []error
-	for _, pkg := range required {
-		graph, err := g.Generate(pkg.Name)
-		if err != nil {
-			errs = append(errs, fmt.Errorf("unable to verify added bundles for package %s: %v", pkg.Name, err))
-			continue
-		}
+checkRequired:
```
Comment (dinhxuanvu) [inline pkg/lib/registry/registry.go:399]: This line and the line 404 look weird. Are these comments?

**Review by dinhxuanvu — COMMENTED** [review]
Looking good. Just a quick question.

File: pkg/lib/registry/registry.go (hunk 1 above)
Comment (kevinrizza) [reply pkg/lib/registry/registry.go:399]: They're go labels https://golang.org/ref/spec#Label_scopes

Comment (dinhxuanvu) [reply pkg/lib/registry/registry.go:399]: I see. Not sure if they are helpful. I would prefer comments. Either way, can we correct the indentation here?

**Review by dinhxuanvu — APPROVED** [review]
/approve

File: pkg/lib/registry/registry_test.go [hunk 2]
```diff
@@ -402,49 +400,42 @@ func TestCheckForBundles(t *testing.T) {
...
+							csvSpec: json.RawMessage(`{"version":"1.2.0"}`),
+							annotations: registry.Annotations{
+								PackageName:        "testpkg",
+								Channels:           "alpha",
+								DefaultChannelName: "stable",
 							},
+							version: "1.2.0",
 						},
 					},
+					action: actionAdd,
```
Comment (kevinrizza) [inline pkg/lib/registry/registry_test.go:436]: Probably outside the scope of this pull request, but it would be nice if we had a way of comparing the contents of the database based on these actions rather than just checking for error conditions.

File: pkg/lib/registry/registry.go [hunk 3]
```diff
@@ -399,34 +393,57 @@ func checkForBundlePaths(querier registry.GRPCQuery, bundlePaths []string) ([]st
...
+	for _, bundle := range required {
+		var graph *registry.Package
+		var deprecated *bool
+		var err error
+	checkForBundleInChannel:
+		for _, channel := range bundle.Channels {
+			if graph == nil {
```
Comment (kevinrizza) [inline pkg/lib/registry/registry.go:406]: Is there a reason not to just do this once before we iterate?

File: pkg/lib/registry/registry_test.go [hunk 4]
```diff
@@ -402,49 +400,42 @@ func TestCheckForBundles(t *testing.T) {
...
-										}: nil,
-									},
-								},
+				},
+			},
+			wantErr: fmt.Errorf("add prunes bundle unorderedReplaces-1.0.0 (unorderedReplaces-1.0.0) from package testpkg, channel stable: this may be due to incorrect channel head (unorderedReplaces-1.1.0, skips/replaces [])"),
+		},
+		{
+			description: "silentPruneForExistingBundle",
+			steps: []step{
```
Comment (kevinrizza) [inline pkg/lib/registry/registry_test.go:409]: Should we also test for the case where we're inserting multiple new bundles into the same graph? Both the failure case (one of those bundles doesn't replace another) and the success case (one of the bundles resets the graph, another gets added on top of it)?

File: pkg/lib/registry/registry_test.go [hunk 5]
```diff
@@ -382,17 +381,65 @@ func TestCheckForBundles(t *testing.T) {
 							},
 							version: "1.1.0",
 						},
-						"unorderedReplaces-1.0.0": {
-							csvSpec: json.RawMessage(`{"version":"1.0.0","replaces":"unorderedReplaces-1.1.0"}`),
+					},
+					action: actionAdd,
+				},
+				{
+					bundles: map[string]bundleDir{
```
Comment (kevinrizza) [inline pkg/lib/registry/registry_test.go:388]: 👍

**Review by kevinrizza — APPROVED** [review]
/lgtm
